#!/usr/bin/env python3
"""master orc"""


import argparse
import orc
import socket
import sys



def parse_arguments():
	"""parse arguments"""

	parser = argparse.ArgumentParser()

	parser.add_argument("--server", default="ws://127.0.0.1:56000/")
	parser.add_argument("--realm", default="orc1")
	parser.add_argument("--schema", default="etc/orcish.schema")
	parser.add_argument("--identity", default=socket.getfqdn())
	parser.add_argument("--ui", default="formed", choices=["formed", "listener", "commander"])
	parser.add_argument("--debug", action="store_true")

	return parser.parse_args()



def main():
	"""main"""

	# args
	args = parse_arguments()
	orc.start_logging(args.debug)

	# startup
	orc.Master().run(args)



if __name__ == "__main__":
	sys.exit(main())
