#!/usr/bin/python
"""tg python trafgen wrapper"""

import argparse
import logging
import sys
import tg

logger = logging.getLogger()
logging.basicConfig(level=logging.INFO, stream=sys.stdout, format='%(levelname)s %(message)s')


def parse_arguments():
	"""parse arguments"""

	parser = argparse.ArgumentParser()
	parser_command = parser.add_subparsers(dest="generator", help="generator name")

	for cls in tg.modreg.registered_classes:
		cls.build_arguments_parser(parser_command.add_parser(cls.__name__))

	return parser.parse_args()



def main():
	"""main"""
	args = parse_arguments()
	if args.debug:
		logger.setLevel(logging.DEBUG)

	generator = getattr(tg, args.generator)(args.__dict__)
	logger.debug("generator fields: %s", generator.fields)

	if args.dump:
		print generator.compile()
	else:
		generator.execute()



if __name__ == "__main__":
	sys.exit(main())
